### PR TITLE
Add .NET Core support - WIP

### PR DESCRIPTION
**Pull request by JosephWoodward**
Initial attempted at adding .NET Standard support - still work in progress.

Shouldly's tests have a dependency on this so as soon as TestStack.ConventionTests supports .NET Standard then people will be able to build/contribute to Shouldly across multiple operating systems so it's a win-win.

This is the first time I've done this so if there are any suggestions then please feel free to fire them my way.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Will be awesome to see this in! Ping me on twitter if you get stuck

**Comment by JosephWoodward** [comment]
Great, will do.

**Comment by JosephWoodward** [comment]
Run into a bit of a blocker in [this class](https://github.com/TestStack/TestStack.ConventionTests/blob/master/TestStack.ConventionTests/Reporting/HtmlConventionResultsReporter.cs#L20) that has a dependency on `HtmlTextWriter` within the  System.Web.UI package. Are you happy for me to replace it with a string builder?

**Comment by drewfreyling** [comment]
FYI This fixes #77

**Comment by JosephWoodward** [comment]
Picked this one up again 👍

**Comment by scpeterson** [comment]
Hello!  I'm curious to know how it's going with the .NET Core support?  I'm interested in contributing to Shouldly and would like to see TestStack.ConventionTests upgraded to .NET Core so I can use it with Shouldly.  Is there anything I can do to help?

**Pull request merged**
