### PR TITLE
Fixes IsStatic() extension method.

### PR DESCRIPTION
**Pull request by lundmikkel**
[Fixes issue with IsStatic() extension method.](https://github.com/TestStack/TestStack.ConventionTests/issues/73)

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Hey, thanks for this.

Would you have time to drop a test in as well for this, it would be handy to increase our test coverage on these sort of utilities. let me know either way

**Comment by JakeGinnivan** [comment]
I have just pushed v3, I will push 3.0.1 once this gets pulled in. Let me know if you plan on adding the test :)

**Comment by lundmikkel** [comment]
Okay, I've thrown together some quick tests. Hope that will at least give you a starting point.

**Comment by lundmikkel** [comment]
How is this issue coming along?

**Comment by JakeGinnivan** [comment]
Thanks for reminding me, will get it released soon!

**Comment by JakeGinnivan** [comment]
Ugh regions, but not gonna stop this getting released because of that :P

**Comment by JakeGinnivan** [comment]
Sorry for taking so long

**Pull request merged**
