### PR TITLE
feat (NetCoreSupport): Continue work done on PR #78 

### PR DESCRIPTION
**Pull request by jafin**
Continue work done on PR #78 to get net core builds.  
* Use SDK 3.1.200 
* Migrate Packages.config to PackageReferences
* Drop binaries from packages 
* Target Framework sample app now 4.7.2 (from 4.0)
* Target netstandard2.0

### CODE REVIEW

**Comment by jafin** [comment]
Relates to #77

**Comment by JosephWoodward** [comment]
Oh nice, is this ready for review/merge?

**Comment by jafin** [comment]
@JosephWoodward It should be good to merge.  Just after a maintainer to review/commit.   Funny, my prime motivation was to update this for Shouldly.   I am unsure if this project is abandoned, the last commit was a few years ago. ?    If no response from maintainers can fork and publish a forked Nuget package but this is not an ideal outcome.

**Comment by JosephWoodward** [comment]
@jafin I think that's a good idea, at least until this gets merged.

**Comment by mwhelan** [comment]
Hi. I'm a TestStack maintainer. I'll take a look at this over the weekend and try to get it merged and released

**Comment by JosephWoodward** [comment]
Oh great, thanks @mwhelan!

**Comment by jafin** [comment]
@mwhelan  Sorry  I misunderstood the versioning process.  DotNet pack wasn't updating the version. I pushed another PR which should correct it.  #81 
I notice the version is obtained from the git tag, I guess I can leave it up to the maintainers to tag (Semver probably major +1)   , it looks to be inheriting 3.0.2 atm.
Also, I haven't changed anything relating to pushing packages to Nuget repository.  I can't see anything automated in the Appveyor that does that, would this be a manual step?

**Comment by mwhelan** [comment]
Thanks @jafin . There are a couple of deployments in appveyor - one to create GitHub release notes and one to push to NuGet. They might be quite out of date after 4 years...

I'll tag this as v4.0.0 and try to release. I would like to upgrade Autofac to 5.1.2. There were breaking changes in Autofac between version 4 and 5 and I'd like to be up-to-date with the latest version. Let me know if you think there might be any issues with doing that.

**Comment by jafin** [comment]
@mwhelan thanks,  If I get time this arvo I can attempt the upgrade to Autofac 5.1.2,  I'll do another PR if so.

**Comment by mwhelan** [comment]
I'm actually just doing it now. All the tests compile fine with it.

**Pull request merged**
